---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[ssh-iam-agent::default]
    attributes: { ssh-iam-agent: { users: [ "fx29491" ] } }
